# Generated by Django 2.1 on 2019-02-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table01',
            fields=[
                ('sno', models.AutoField(help_text='学号', primary_key=True, serialize=False, verbose_name='学号')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('date01', models.DateField()),
                ('date02', models.DateTimeField()),
                ('money', models.FloatField()),
                ('IsReady', models.BooleanField()),
                ('desc', models.TextField(null=True)),
            ],
        ),
    ]
