# Generated by Django 2.1 on 2019-02-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_table01'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table02',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('stuclass', models.CharField(default='二年级', max_length=100)),
                ('mobile', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('date01', models.DateTimeField(auto_now_add=True)),
                ('date02', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
