# Generated by Django 2.1 on 2019-02-27 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_table02'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table02',
        ),
    ]
