# Generated by Django 2.0 on 2019-12-11 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名字')),
                ('gender', models.IntegerField(verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
            ],
        ),
        migrations.CreateModel(
            name='HeroType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5, verbose_name='名称')),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='ht',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HeroType'),
        ),
    ]
