# Generated by Django 2.1.5 on 2019-12-12 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='技能名字')),
                ('cd', models.IntegerField(verbose_name='冷却时间')),
                ('da', models.IntegerField(verbose_name='伤害值')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hero')),
            ],
        ),
    ]
