# Generated by Django 2.1.5 on 2019-12-12 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grades',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stu.Grades'),
            preserve_default=False,
        ),
    ]
