#!/bin/bash
# 备份指定目录的文件，然后传递到FTP服务器上，再发送邮件

# 要备份的目录，多个文件夹之间使用空格为分隔，例如: /home /www /data2
BACKUP="/home /root"

# 远程的ftp服务器
FTPH="192.168.1.250"
# FTP用户名
FTPU="chentao"
# FTP密码
FTPP="ct7273612"
# 远程FTP服务器的目录
FTPD="backup/"

# 临时工作目录
TMPD="/tmp"

# 邮件
# 接收人
MTO="tom_chen@126.com"
# 邮件主题
MSUB="Backup $(hostname) report"

# 不同的Linux发行版本可能会有区别
TAR="/usr/bin/tar"
MAILC="/usr/bin/mail"
NCFTP="/usr/bin/ncftpput"

######################################
# 下面的代码无需进行修改
######################################
BAKFILE="$(hostname).$(date +"%Y-%m-%d").tar.gz"
FOUT="$TMPD/$BAKFILE"
MFILE="/tmp/ftpout.$$.txt"
MESS=""

if [ ! -x $TAR ]; then
  echo "$TAR commnad not found!"
  exit 1
fi 

if [ ! -x $NCFTP ]; then
  echo "$NCFTP commnad not found!"
  exit 1
fi 
if [ ! -x $MAILC ]; then
  echo "$MAILC commnad not found!"
  exit 1
fi 

$TAR -zcf $FOUT $BACKUP
# 步步为营，先保证压缩是成功的

if [ $? -ne 0 ] ; then
  MESS="$TAR failed to create backup. Nothing uploaded to FTP $FTPH server"
else
  # 可以考虑在上传文件之前对文件进行加密
  # 上传文件
  $NCFTP -m -u "$FTPU" -p "$FTPP" "$FTPH" "$FTPD" "$FOUT"
  OSTAT="$?"
  
  case $OSTAT in
    0) MESS="Success." ;;
    1) MESS="Could not connect to remote host $FTPH.";;
    2) MESS="Could not connect to remote host $FTPH - timed out.";;
    3) MESS="Transfer failed.";;
    4) MESS="Transfer failed - timed out.";;
    5) MESS="Directory change failed.";;
    6) MESS="Directory change failed - timed out.";;
    7) MESS="Malformed URL.";;
    8) MESS="Usage error. May be your version of ncftpput ($NCFTP) is old";;
    9) MESS="Error in login configuration file.";;
    10) MESS="Library initialization failed.";;
    11) MESS="Session initialization failed.";;
    *) MESS="Unknown error, contact admin $ADMIN_INFO";;
  esac
fi 

# 生成操作日志文件
>$MFILE
echo "Backup status for $(hostname) as on $(date):" >>$MFILE
echo "" >>$MFILE
echo "Backup File: $FOUT" >>$MFILE
echo "Backup FTP Server: $FTPH" >>$MFILE
echo "Backup status message: $MESS" >>$MFILE
echo "" >>$MFILE
echo "-- Automatically generated by $(basename $0)" >>$MFILE

# 发送通知邮件
$MAILC -s "$MSUB" $MTO <$MFILE

# 删除文件
[ -f $MFILE ] && rm -f $MFILE
[ -f $FOUT ] && rm -f $FOUT

exit 0
