# Generated by Django 2.1 on 2020-01-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.IntegerField(db_column='SNo', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='SName', max_length=100)),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], db_column='Gender', max_length=100)),
                ('birthday', models.DateField(db_column='Birthday')),
                ('mobile', models.CharField(db_column='Mobile', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('address', models.CharField(db_column='Address', max_length=200)),
                ('image', models.CharField(db_column='Image', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Student',
                'managed': True,
            },
        ),
    ]
