# Generated by Django 2.1.5 on 2019-12-16 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('ext', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='扩展字段')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('position', models.IntegerField(default=0, verbose_name='排序')),
                ('href', models.URLField(verbose_name='跳转地址')),
            ],
            options={
                'verbose_name': '导航',
                'verbose_name_plural': '导航',
            },
        ),
        migrations.CreateModel(
            name='NavCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('ext', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='扩展字段')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('position', models.IntegerField(default=0, verbose_name='排序')),
                ('vnum', models.IntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '导航分类',
                'verbose_name_plural': '导航分类',
            },
        ),
        migrations.AddField(
            model_name='nav',
            name='nav_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.NavCategory'),
        ),
    ]
