# Generated by Django 2.1 on 2019-02-27 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminmodules',
            fields=[
                ('moduleid', models.AutoField(db_column='ModuleId', primary_key=True, serialize=False)),
                ('modulename', models.CharField(db_column='ModuleName', max_length=100)),
                ('url', models.CharField(db_column='URL', max_length=100)),
                ('icon', models.CharField(db_column='ICON', max_length=100)),
                ('priority', models.IntegerField(blank=True, db_column='Priority', null=True)),
            ],
            options={
                'db_table': 'AdminModules',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('loginid', models.CharField(db_column='LoginId', max_length=20, primary_key=True, serialize=False)),
                ('loginpwd', models.CharField(db_column='LoginPwd', max_length=20)),
                ('username', models.CharField(db_column='UserName', max_length=20)),
                ('isenable', models.IntegerField(db_column='IsEnable')),
                ('createtime', models.DateTimeField(blank=True, db_column='CreateTime', null=True)),
                ('lastlogintime', models.DateTimeField(blank=True, db_column='LastLoginTime', null=True)),
            ],
            options={
                'db_table': 'Login',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('positionid', models.AutoField(db_column='PositionId', primary_key=True, serialize=False)),
                ('positionname', models.CharField(db_column='PositionName', max_length=20)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Position',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.CharField(db_column='ProductId', max_length=20, primary_key=True, serialize=False)),
                ('barcode', models.CharField(db_column='BarCode', max_length=20, unique=True)),
                ('productname', models.CharField(db_column='ProductName', max_length=200)),
                ('unit', models.CharField(db_column='Unit', max_length=20)),
                ('unitprice', models.FloatField(db_column='UnitPrice')),
                ('inventory', models.IntegerField(db_column='Inventory')),
            ],
            options={
                'db_table': 'Product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productcategory',
            fields=[
                ('categoryid', models.AutoField(db_column='CategoryId', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(db_column='CategoryName', max_length=100)),
                ('decription', models.CharField(blank=True, db_column='Decription', max_length=200, null=True)),
            ],
            options={
                'db_table': 'ProductCategory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Saleslist',
            fields=[
                ('serialnumber', models.CharField(db_column='SerialNumber', max_length=20, primary_key=True, serialize=False)),
                ('totalnumber', models.IntegerField(db_column='TotalNumber')),
                ('totalprice', models.FloatField(db_column='TotalPrice')),
                ('receivemoney', models.FloatField(db_column='ReceiveMoney')),
                ('returnmoney', models.FloatField(db_column='ReturnMoney')),
                ('buytime', models.DateTimeField(blank=True, db_column='BuyTime', null=True)),
                ('loginid', models.ForeignKey(blank=True, db_column='LoginId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Login')),
            ],
            options={
                'db_table': 'SalesList',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Saleslistdetail',
            fields=[
                ('detailid', models.AutoField(db_column='DetailId', primary_key=True, serialize=False)),
                ('productname', models.CharField(db_column='ProductName', max_length=200)),
                ('unit', models.CharField(db_column='Unit', max_length=20)),
                ('unitprice', models.FloatField(db_column='UnitPrice')),
                ('number', models.IntegerField(db_column='Number')),
                ('money', models.FloatField(db_column='Money')),
                ('productid', models.ForeignKey(blank=True, db_column='ProductId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Product')),
                ('serialnumber', models.ForeignKey(blank=True, db_column='SerialNumber', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Saleslist')),
            ],
            options={
                'db_table': 'SalesListDetail',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categoryid',
            field=models.ForeignKey(blank=True, db_column='CategoryId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Productcategory'),
        ),
        migrations.AddField(
            model_name='login',
            name='positionid',
            field=models.ForeignKey(db_column='PositionId', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Position'),
        ),
    ]
