# Generated by Django 3.1.5 on 2022-02-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userweb', '0002_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
