# Generated by Django 3.1.5 on 2022-03-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userweb', '0004_menu_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='account',
            field=models.ManyToManyField(null=True, to='userweb.Account', verbose_name='账号'),
        ),
    ]
