# Generated by Django 2.1.5 on 2019-12-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(max_length=15, verbose_name='昵称')),
                ('pwd', models.CharField(max_length=64, verbose_name='密码')),
                ('gender', models.CharField(choices=[(0, '男'), (1, '女')], max_length=10, verbose_name='性别')),
                ('hobby', models.CharField(max_length=255, verbose_name='爱好')),
                ('avator', models.ImageField(upload_to='upload/%Y/%m/%d', verbose_name='头像')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
