# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_hotsearchwords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotsearchwords',
            old_name='add',
            new_name='add_time',
        ),
    ]
