# Generated by Django 2.1 on 2019-02-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(max_length=100, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('mobile', models.CharField(max_length=100, unique=True, verbose_name='手机号码')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='邮箱地址')),
                ('address', models.CharField(max_length=200, verbose_name='家庭住址')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
