# Generated by Django 2.1 on 2019-02-27 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarydb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('city', models.CharField(max_length=100, verbose_name='所在城市')),
                ('telno', models.CharField(max_length=100, verbose_name='联系电话')),
                ('email', models.CharField(max_length=100, verbose_name='邮箱地址')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
            ],
            options={
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False, verbose_name='图书编号')),
                ('bookname', models.CharField(db_index=True, max_length=200, verbose_name='图书名称')),
                ('storagein', models.IntegerField(verbose_name='入库量')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarydb.Author')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类别名称')),
            ],
            options={
                'db_table': 'BookType',
            },
        ),
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowdate', models.DateTimeField(verbose_name='借书时间')),
                ('returndate', models.DateTimeField(verbose_name='归还时间')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarydb.Book')),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarydb.Student')),
            ],
            options={
                'db_table': 'BorrowBook',
            },
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='出版社名称')),
                ('city', models.CharField(max_length=100, verbose_name='所在城市')),
                ('telno', models.CharField(max_length=100, verbose_name='联系电话')),
                ('email', models.CharField(max_length=100, verbose_name='邮箱地址')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
            ],
            options={
                'db_table': 'Press',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='booktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarydb.BookType'),
        ),
        migrations.AddField(
            model_name='book',
            name='press',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarydb.Press'),
        ),
    ]
