# Generated by Django 2.1 on 2019-02-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarydb', '0002_auto_20190227_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='价格'),
            preserve_default=False,
        ),
    ]
