# Generated by Django 2.1.5 on 2019-12-17 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artcile',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AddField(
            model_name='artcile',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 1, 39, 55, 26555), verbose_name='创建日期'),
        ),
    ]
