# Generated by Django 2.1.5 on 2019-12-17 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191217_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AlterField(
            model_name='artcile',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 2, 56, 25, 470056), verbose_name='创建日期'),
        ),
        migrations.AddField(
            model_name='artcile',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='属于标签'),
        ),
    ]
