# Generated by Django 3.1.5 on 2021-02-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=100, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('mobile', models.CharField(max_length=100, verbose_name='手机号码')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱地址')),
                ('address', models.CharField(max_length=250, verbose_name='手机号码')),
                ('start_date', models.DateField(verbose_name='入学时间')),
                ('status', models.CharField(choices=[('在校', '在校'), ('毕业', '毕业'), ('休学', '休学'), ('开除', '开除')], default='在校', max_length=100, verbose_name='状态')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicweb.faculty', verbose_name='院系名称')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicweb.major', verbose_name='所学专业')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Student',
                'db_table': 'Stu_Student',
                'managed': True,
            },
        ),
    ]
