# Generated by Django 2.1.5 on 2019-12-25 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app05', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gun',
            name='gt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app05.GunType', verbose_name='属于种类'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gun',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名字'),
        ),
    ]
