# Generated by Django 2.1.5 on 2019-12-13 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('ext', models.CharField(default='{}', max_length=1024, verbose_name='扩展字段')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='名字')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='名字')),
                ('name', models.CharField(max_length=6, unique=True, verbose_name='名字')),
                ('position', models.IntegerField(verbose_name='排序')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('ext', models.CharField(default='{}', max_length=1024, verbose_name='扩展字段')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='名字')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='名字')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('content', models.TextField(max_length=4000, verbose_name='内容')),
                ('src', models.URLField(verbose_name='封面')),
                ('vnum', models.IntegerField(default=0, verbose_name='浏览量')),
                ('isoriginal', models.BooleanField(verbose_name='是否原创')),
                ('istop', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
    ]
