# Generated by Django 2.1.5 on 2019-12-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('avator', models.ImageField(upload_to='upload/%Y/%m/%d', verbose_name='头像')),
            ],
        ),
    ]
