# Generated by Django 2.1.5 on 2019-12-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
    ]
