# Generated by Django 2.1 on 2019-02-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('学号', models.IntegerField(primary_key=True, serialize=False)),
                ('姓名', models.CharField(max_length=100)),
                ('性别', models.CharField(max_length=100)),
                ('出生日期', models.DateField()),
                ('手机号码', models.CharField(max_length=100)),
                ('邮箱地址', models.CharField(max_length=100)),
                ('家庭住址', models.CharField(max_length=200)),
            ],
        ),
    ]
