# Generated by Django 2.1 on 2019-02-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='家庭住址',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='出生日期',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='姓名',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='性别',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='手机号码',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='邮箱地址',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='学号',
            new_name='sno',
        ),
    ]
