# Generated by Django 3.1.5 on 2021-08-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='图片名称')),
                ('remark', models.CharField(blank=True, max_length=250, null=True, verbose_name='标注')),
                ('create_time', models.DateTimeField(verbose_name='上传时间')),
            ],
            options={
                'verbose_name': 'StudentImage',
                'verbose_name_plural': 'StudentImage',
                'db_table': 'Stu_StudentImage',
                'managed': True,
            },
        ),
    ]
