# Generated by Django 2.1.5 on 2019-12-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('pwd', models.CharField(max_length=64, verbose_name='密码')),
                ('gender', models.CharField(max_length=3, verbose_name='性别')),
                ('hobby', models.CharField(max_length=128, verbose_name='爱好')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
