# Generated by Django 2.1.5 on 2019-12-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='猫')),
            ],
            options={
                'verbose_name': '猫',
                'verbose_name_plural': '猫',
            },
        ),
    ]
