# Generated by Django 3.1.5 on 2021-02-01 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='院系名称')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculty',
                'db_table': 'Basic_Faculty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='专业名称')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicweb.faculty', verbose_name='所属院系')),
            ],
            options={
                'verbose_name': 'Major',
                'verbose_name_plural': 'Major',
                'db_table': 'Basic_Major',
                'managed': True,
            },
        ),
    ]
