# Generated by Django 2.1.5 on 2019-12-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名字')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('edu', models.IntegerField(choices=[(0, '小学'), (1, '初中'), (2, '高中'), (3, '本科'), (4, '硕士'), (5, '博士')], verbose_name='学历')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '未知')], verbose_name='性别')),
                ('hobby', models.TextField(verbose_name='爱好')),
            ],
        ),
    ]
