# Generated by Django 2.1.5 on 2019-12-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '简历', 'verbose_name_plural': '简历'},
        ),
    ]
