# Generated by Django 3.1.5 on 2021-08-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('loginid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='登陆账号')),
                ('loginpwd', models.CharField(max_length=200, verbose_name='密码')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('status', models.BooleanField(default=0, verbose_name='状态')),
                ('department', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='部门')),
                ('position', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='职位')),
                ('mobile', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='手机号码')),
                ('email', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='邮箱地址')),
                ('last_login', models.DateTimeField(blank=True, default=None, null=True, verbose_name='上次登陆时间')),
                ('create_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Account',
                'db_table': 'user_Account',
                'managed': True,
            },
        ),
    ]
